### ISSUE TITLE
Error while evaluating a Virtual Query

### ISSUE THREAD

**Issue by robinbohnen** [sensson/sensson-directadmin#12]
Hi,

On a puppet 3.8.4 agent i'm getting the following error:
puppet-agent[13826]: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/directadmin_reseller: Could not autoload puppet/provider/directadmin_reseller/directadmin: no such file to load -- puppet/provider/directadmin at /etc/puppetlabs/code/environments/production/modules/directadmin/manifests/init.pp:32:106 on node xx

I've got no clue how to fix this. 

Also second bug which I fixed;
For the $::operatingsystemmajrelease in manifests/install.pp
You need to use instead (3 times, for version 5,6,7): 
if versioncmp($::operatingsystemmajrelease, '5') == 0 {

**Comment by sensson** [comment]
I can't replicate these bugs on our systems. We're using 3.8.4 too though our master is a little older. Can you provide some more detail on the versions you use and possibly the OS too?

**Comment by robinbohnen** [comment]
As master we use: 4.2.3 (on CentOS Linux release 7.1.1503)
As client we use: 3.8.4 (on CloudLinux Server release 6.7)

**Comment by sensson** [comment]
The issue isn't the agent, it's the master. We haven't tested our modules on version 4 as many things have been changed. We will probably support it in the future, but not yet, unless someone comes with a pull request.

**Comment by sensson** [comment]
We've ran some basic tests on a Puppet master with version 3.6 and 3.8 and both seem to be working as expected now. 3.8 gave the exact same error as you had on 4.2 so I assume the issue is resolved now.

@robinbohnen would you mind testing the commit on your environment as well?
