### ISSUE TITLE
Syntax error at 'clientid' 

### ISSUE THREAD

**Issue by paragonil** [sensson/sensson-directadmin#2]
Hey,
I'm trying to use your puppet module but after installing the module to the server and adding it into the manifest, the clients recives error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not parse for environment production: Syntax error at 'clientid' at /etc/puppetlabs/code/environments/production/manifests/site.pp:4:5 on node puppetclient

The /etc/puppetlabs/code/environments/production/manifests/site.pp contatins your example:
class { 'directadmin:'
    clientid       => '1000',
    licenseid      => '10000',
    interface      => 'eth0',
    auto_update    => true,
    admin_password => 's0m3p4ssw0rd',
}

What am I doing wrong?
Thanks.

**Comment by sensson** [comment]
There seems to be a typo in our example. Instead of using

```
class { 'directadmin:'
```

It should be

```
class { 'directadmin':
```

We've updated the example just now.
