### ISSUE TITLE
Cloudlinux support

### ISSUE THREAD

**Issue by robinbohnen** [sensson/sensson-directadmin#3]
Thanks for the great work.
Could you add Cloudlinux support? It's basically the same and 6.x and 7.x are both supported by DirectAdmin.

**Comment by sensson** [comment]
We're more than happy to add it, but I'm afraid we don't have any CloudLinux servers available to test this on.

**Comment by robinbohnen** [comment]
It's not difficult, it's the same as CentOS7. I've just changed:
if $::operatingsystem == 'CentOS' {
to:
if $::operatingsystem == 'CentOS' or $::operatingsystem == 'CloudLinux' {

In file: manifests/install.pp
That's it :)
