### ISSUE TITLE
Creating packages doesn't work with SSL enabled in directadmin.conf

### ISSUE THREAD

**Issue by robinbohnen** [sensson/sensson-directadmin#4]
https connections won't establish. You need to disable SSL to let it work.

**Comment by sensson** [comment]
Good catch, thanks. I'll add it to our roadmap.

**Comment by lifeforms** [comment]
I've had the same problem. DirectAdmin sends a redirect to HTTPS, which is not followed. Another problem occurs if you connect to localhost (CN mismatch).

If you know that you'll always going to be using SSL, you can hack the following in `lib/puppet/provider/directadmin.rb`. This forces https when talking to the API, and disables verification ONLY in case it connects to localhost.

``` ruby
  def self.connect(username, password, hostname, port)
    @auth_username = username
    @auth_password = password
    @http = Net::HTTP.new(hostname, port)
    @http.use_ssl = true
    if hostname == 'localhost'
      # When connecting to localhost, the certificate CN will not match.
      # Skip the check ONLY in this case.
      @http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    end
  end
```

A real clean solution would be to pass an `api_ssl` parameter everywhere.

**Comment by sensson** [comment]
I've just pushed the commit that adds an `api_ssl` parameter to all resources. It adds the functionality @lifeforms has shared.
